"""Add Student grade name

Revision ID: 92fddbb46de7
Revises: e2aecc16cfb8
Create Date: 2024-04-17 12:46:25.845445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fddbb46de7'
down_revision = 'e2aecc16cfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('grade_name')

    # ### end Alembic commands ###
