"""update user table

Revision ID: c93f6f81eaa4
Revises: 4a8aaba0214b
Create Date: 2024-03-29 23:02:41.223417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93f6f81eaa4'
down_revision = '4a8aaba0214b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.String(length=64), nullable=True))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
