"""Add exam_type1

Revision ID: d659bbcdcc63
Revises: a57b5b4c72d6
Create Date: 2024-03-31 08:15:39.713057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd659bbcdcc63'
down_revision = 'a57b5b4c72d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_type1', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('exam_type1')

    # ### end Alembic commands ###
