"""Change school_code to Integer type

Revision ID: f93eefc43caa
Revises: 49a43d4d7f00
Create Date: 2024-12-18 11:11:37.305924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93eefc43caa'
down_revision = '49a43d4d7f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school_code',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
